spring:
  config:
    import: optional:classpath:.env
  datasource:
    url: jdbc:mysql://localhost:3306/telegram_bot
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: classpath:db/changelog/v0.0.1-SNAPSHOT/v0.0.1-master.xml